apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql
  template:
    metadata:
      labels:
        app: graphql
    spec:
      containers:
        - name: graphql
          image: quangdvn/gns-graphql
          imagePullPolicy: Always
          env:
            - name: APP_PORT
              value: "4000"
            - name: SESSION_NAME
              value: qid
            - name: SESSION_SECRET
              value: quangdvn
            - name: JWT_SECRET
              value: quangdvn
            - name: REDIS_HOST
              value: redis-17417.c93.us-east-1-3.ec2.cloud.redislabs.com
            - name: REDIS_PORT
              value: "17417"
            - name: REDIS_PASSWORD
              value: "123456"
            - name: DRIVER_URL
              value: http://driver-serv:3000
            - name: STAFF_URL
              value: http://staff-serv:3000
            - name: AUTH_URL
              value: http://auth-serv:3000
---
apiVersion: v1
kind: Service
metadata:
  name: graphql-serv
spec:
  selector:
    app: graphql
  type: NodePort
  ports:
    - name: graphql
      nodePort: 30303
      port: 4000
      targetPort: 4000
