name: trip-deploy

on:
  push:
    branches:
      - main
    paths:
      - "trip/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build Image
        run: cd trip && docker build -t quangdvn/gns-trip .
      - name: Log in Docker Hub
        run: docker login -u $DOCKER_ID -p $DOCKER_PASSWORD
        env:
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        run: docker push quangdvn/gns-trip
      - name: Install Doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}
      - name: Save new cluster
        run: doctl kubernetes cluster kubeconfig save go-n-share
      - name: Get k8s nodes
        run: kubectl get nodes
      - name: Restart k8s cluster
        run: kubectl rollout restart deployment trip-depl
